version: '3'

services:
  food-order-api:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_order
    volumes: 
      - ./food-order.sql:/docker-entrypoint-initdb.d/food-order.sql
    ports:
      - "3306:3306"
